from .frozenlake_oracle import analyze_frozenlake_grid
from .gym_cards_oracle import get_next_action_for_ezpoints
from .minigrid_oracle import get_fetch_oracle_action, get_lavagap_oracle_action, get_gotodoor_oracle_action
